# Generated by Django 5.1.2 on 2025-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0002_party_guest_gift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
